/**
 * ResetPasswordPage constants
 */

export const RESET_PASSWORD_REQUEST = 'app/ResetPasswordPage/RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'app/ResetPasswordPage/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'app/ResetPasswordPage/RESET_PASSWORD_ERROR';
export const AUTHENTICATE_RESET_PASSWORD_TOKEN = 'app/ResetPasswordPage/AUTHENTICATE_RESET_PASSWORD_TOKEN';
export const AUTHENTICATE_RESET_PASSWORD_TOKEN_SUCCESS = 'app/ResetPasswordPage/AUTHENTICATE_RESET_PASSWORD_TOKEN_SUCCESS';
export const AUTHENTICATE_RESET_PASSWORD_TOKEN_ERROR = 'app/ResetPasswordPage/AUTHENTICATE_RESET_PASSWORD_TOKEN_ERROR';
