/**
 * ResetPasswordPage constants
 */

export const DEFAULT_ACTION = 'app/ResetPasswordPage/DEFAULT_ACTION';
export const AUTHENTICATE_RESET_PASSWORD_TOKEN = 'app/ResetPasswordPage/AUTHENTICATE_RESET_PASSWORD_TOKEN';
export const AUTHENTICATE_RESET_PASSWORD_TOKEN_SUCCESS = 'app/ResetPasswordPage/AUTHENTICATE_RESET_PASSWORD_TOKEN_SUCCESS';
export const AUTHENTICATE_RESET_PASSWORD_TOKEN_ERROR = 'app/ResetPasswordPage/AUTHENTICATE_RESET_PASSWORD_TOKEN_ERROR';
