
export const SET_PASSWORD_REQUEST = 'app/ConfirmAccountPage/SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS = 'app/ConfirmAccountPage/SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_ERROR = 'app/ConfirmAccountPage/SET_PASSWORD_ERROR';
export const AUTHENTICATE_CONFIRM_ACCOUNT_TOKEN = 'app/ConfirmAccountPage/AUTHENTICATE_CONFIRM_ACCOUNT_TOKEN';
export const AUTHENTICATE_CONFIRM_ACCOUNT_TOKEN_SUCCESS = 'app/ConfirmAccountPage/AUTHENTICATE_CONFIRM_ACCOUNT_TOKEN_SUCCESS';
export const AUTHENTICATE_CONFIRM_ACCOUNT_TOKEN_ERROR = 'app/ConfirmAccountPage/AUTHENTICATE_CONFIRM_ACCOUNT_TOKEN_ERROR';
